parser: 'babel-eslint'
env:
  node: true
  mocha: true
extends:
    - 'eslint:recommended'
    - 'prettier'
parserOptions:
    ecmaFeatures:
        experimentalObjectRestSpread: true
    sourceType: module
rules:
    no-console:
        - 1
        - allow:
              - warn
              - error
    indent:
        - warn
        - 4
        - SwitchCase: 1
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - always
    no-debugger: 1
