# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:11.0     
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install --loglevel error
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run lint:ci
      - store_test_results:
          path: ~/repo/reports/eslint
      - store_artifacts:
          path: ~/repo/reports/eslint

  test:
    docker:
      - image: circleci/node:11.0     
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install --loglevel error
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          command: npm run test:ci
          environment:
            MOCHA_FILE: ./reports/tests/test-results.xml
      - store_test_results:
          path: ~/repo/reports/tests
      - store_artifacts:
          path: ~/repo/reports/tests

  build:
    docker:
      - image: circleci/node:11.0     
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install --loglevel error
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - lint
      - build:
          requires:
            - test
            - lint     


